config/routes.rb
Rails.application.routes.draw do
  root to: 'homes#top'
  resources:books
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord

  validates :title, presence: true
  validates :body, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  def create
    @book = Book.new(book_params)
    if @book.save
    flash[:notice] = "Book was successfully created."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :index
    end
  end

  def index
    @books = Book.all
    @book = Book.new
  end

  def show
      @book = Book.find(params[:id])
  end

  def edit
      @book = Book.find(params[:id])
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    redirect_to '/books'
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
    flash[:notice] = "Book was successfully updated."
    redirect_to book_path(@book.id)
    else
    @books = Book.all
    render :edit
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/views/books/edit.html.erb
<h1 class = "edit-h1">Editing Books</h1>

<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

<%= form_with model: @book do |f| %>
<h4>Title</h4>
<p class="edit-box"><%= f.text_field :title %></p>
<h4>Body</h4>
<p class="edit-box"><%= f.text_area :body %></p>

<p class = "edit-update"><%= f.submit 'Update Book' %></p>
<% end %>

<p class = "edit-p"><%= link_to "Show", book_path(@book.id), class: "editshow" %></p>
<p class = "edit-p">|</p>
<p class = "edit-p"><%= link_to "Back", "/books" %></p>

app/views/books/index.html.erb
<h1 class="index-h1">Books</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @books.each do |book| %>
      <tr>
        <td class = "title-body"><%= book.title %></td>
        <td class = "title-body"><%= book.body %></td>
        <td><%= link_to "Show", book_path(book.id), class: "link" %></td>
        <td><%= link_to "Edit", edit_book_path(book.id), class: "link" %></td>
        <td><%= link_to "Destroy", book_path(book.id), class: "link", method: :delete,  "data-confirm" => "Are you sure?"%></td>
      </tr>
    <% end %>
  </tbody>
</table>

<h2 class ="index-h2">New book</h2>
<% if @book.errors.any? %>
  <%= @book.errors.count %> errors prohibited this book from being saved:
  <ul>
    <% @book.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>


<%= form_with model: @book, url: '/books', method: :post do |f| %>
  <h4>Title</h4>
  <p class="index-p"><%= f.text_field :title %></p>
  <h4>Body</h4>
  <p class="index-p"><%= f.text_area :body %></p>

  <p class="index-p2"><%= f.submit 'Create Book' %></p>
<% end %>

app/views/books/show.html.erb
<h4 class = "show-h4">Title: </h4>
  <p class = "show-p"><%= @book.title %></p>
<br>
<h4 class = "show-h4">Body: </h4>
  <p class = "show-p"><%= @book.body %></p>
<br>
<p class = "show-p"><%= link_to "Edit", edit_book_path(@book.id), class: "showedit" %></p>
<p class = "show-p">|</p>
<p class = "show-p"><%= link_to "Back", "/books" %></p>

app/views/homes/top.html.erb
<h2 class="top-h2">ようこそ Bookers へ！</h2>
<p class="top-p"><b>Bookers</b> では、さまざまな書籍に関するあなたの意見や</p>
<p class="top-p">印象を共有し交換することが出来ます</p>

<p class="top-p"><%= link_to "Start", books_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bookers</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div>
      <%= flash[:notice] %>
    </div>
    <%= yield %>
  </body>
</html>